version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: monthly
      labels:
          - dependencies
    - package-ecosystem: pip
      directory: /.github/workflows
      schedule:
          interval: monthly
      labels:
          - dependencies
    - package-ecosystem: pip
      directory: /docs
      schedule:
          interval: monthly
      labels:
          - dependencies
    - package-ecosystem: pip
      directory: /
      schedule:
          interval: monthly
      versioning-strategy: lockfile-only
      allow:
          - dependency-type: all
      labels:
          - dependencies
