services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CAMPLY_API_URL=http://backend:8000/api
    image: juftin/camply-frontend:${FRONTEND_VERSION:-local}
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy
