branches:
    - main
    - master
    - next
    - next-major
    - +([0-9])?(.{+([0-9]),x}).x
    - name: beta
      prerelease: true
    - name: alpha
      prerelease: true
plugins:
    - semantic-release-gitmoji
    - - "@semantic-release/exec"
      - prepareCmd: bash .github/semantic_release/set_version.sh ${nextRelease.version} && poetry build
    - - "@semantic-release/git"
      - assets:
            - pyproject.toml
            - camply/_version.py
        message: |
            🔖 camply ${nextRelease.version}

            ${nextRelease.notes}
            [skip ci]
    - - "@semantic-release/github"
      - assets:
            - path: dist/*.whl
            - path: dist/*.tar.gz
