name: "camply-web"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: juftin/camply-web-backend:${BACKEND_VERSION:-local}
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - CAMPLY_API_URL=http://backend:8000/api
    image: juftin/camply-web-frontend:${FRONTEND_VERSION:-local}
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
