# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  frontend:
    taskfile: frontend/Taskfile.yaml
    dir: frontend
  backend:
    taskfile: backend/Taskfile.yaml
    dir: backend

vars:
  DOCKER_ORG: juftin
  DOCKER_REPO: camply-web

tasks:
  install:
    desc: Install All Dependencies (Backend + Frontend)
    cmds:
      - task: backend:install
      - task: frontend:install

  test:
    desc: Run All Tests (Backend + Frontend)
    cmds:
      - task: backend:test
      - task: frontend:test

  lint:
    desc: Lint All Code (Backend + Frontend)
    cmds:
      - task: backend:lint
      - task: frontend:lint

  check:
    desc: Run Type Checking (Backend + Frontend)
    cmds:
      - task: backend:check
      - task: frontend:check

  fix:
    desc: Fix All Code with Linters and Formatters
    deps:
      - task: backend:fix
      - task: frontend:fix

  build:
    desc: Build the Project Artifacts
    cmds:
      - task: backend:build
      - task: frontend:build

  publish:
    desc: Publish the Project Artifacts
    cmds:
      - echo "Publishing Project Artifacts..."
    deps: [build]
    requires:
      vars: [CI]

  version:
    desc: Get/Set Project Versions
    cmds:
      - task: backend:version

  pre-commit:
    desc: Run Pre-Commit Hooks
    cmds:
      - uv tool run --isolated pre-commit run {{.CLI_ARGS}}
    status:
      - test ! -f .pre-commit-config.yaml
    deps: [pre-commit-install]

  dev:
    desc: Run Full Stack Development (Backend + Frontend)
    deps: ["frontend:dev", "backend:debug"]

  run:
    desc: Run the project with Docker Compose
    cmds:
      - docker compose up --build

  default:
    desc: Install Project, List Tasks
    cmds:
      - task --list-all
    deps: [install]

  ########################
  # INTERNAL TASKS
  ########################

  pre-commit-install:
    desc: Install Pre-Commit Hooks
    internal: true
    cmds:
      - cmd: |
          if [ "{{.SKIP_PRECOMMIT | default 0}}" = "0" ]; then
              uv tool run --isolated pre-commit install --install-hooks
          fi
        silent: true
    status:
      - test ! -f ../.pre-commit-config.yaml
