# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  SOURCE_CODE: src/camply_web
  DOCKER_ORG: juftin
  DOCKER_REPO: camply-web
env:
  UV_LOCKED: 1
tasks:
  install:
    desc: Install Project + Dev Dependencies
    cmds:
      - task: pre-commit-install
    deps: [sync]
  test:
    desc: Run Tests
    cmds:
      - uv run --all-extras -- pytest {{.CLI_ARGS | default "tests"}}
    deps: [sync]
  fix:
    desc: Fix Code with Linters and Formatters
    cmds:
      - task: fmt
      - uv run -- ruff check --fix {{.CLI_ARGS | default .ROOT_DIR}}
      - task: pre-commit
    deps: [sync]
  lint:
    desc: Run Code Linters
    cmds:
      - uv run -- ruff check {{.CLI_ARGS | default .ROOT_DIR}}
      - task: check
    deps: [sync]
  build:
    desc: Build the Project Artifacts
    cmds:
      - uv build
      - task: docker
  run:
    desc: Run Command within Project (requires "--")
    cmds:
      - uv run -- {{.CLI_ARGS}}
    deps: [sync]
  publish:
    desc: Publish the Project Artifacts
    cmds:
      - echo "Publishing Project Artifacts..."
    deps: [build]
    requires:
      vars: [CI]
  version:
    desc: View / Set Project Version
    cmd: uv tool run --isolated hatch version {{.CLI_ARGS}}
    silent: true
  pre-commit:
    desc: Run Pre-Commit Hooks
    cmds:
      - uv tool run --isolated pre-commit run
    status:
      - test ! -f {{.ROOT_DIR}}/.pre-commit-config.yaml
    deps: [pre-commit-install]
  default:
    desc: Install Project, List Tasks
    cmds:
      - task --list-all
    deps: [sync]
  docker:
    desc: Build Docker Image
    cmds:
      - |
        docker build \
           --tag {{.DOCKER_ORG}}/{{.DOCKER_REPO}}:latest \
           --tag {{.DOCKER_ORG}}/{{.DOCKER_REPO}}:{{.PACKAGE_VERSION}} \
           {{.CLI_ARGS}} \
           {{.ROOT_DIR}}
    status:
      - test ! -f {{.ROOT_DIR}}/{{.DOCKERFILE | default "Dockerfile"}}
    vars:
      PACKAGE_VERSION:
        sh: uv tool run --isolated hatch project metadata version
  check:
    desc: Run Static Type Checkers
    cmds:
      - |
        uv run -- \
        mypy \
          --install-types \
          --ignore-missing-imports \
          --non-interactive \
          {{.CLI_ARGS | default .SOURCE_CODE}}
    deps: [sync]
  fmt:
    desc: Run Code Formatters
    cmds:
      - uv run -- ruff format {{.CLI_ARGS | default .ROOT_DIR}}
    deps: [sync]
  ########################
  # APP TASKS
  ########################
  debug:
    desc: Run the Project in Debug Mode
    cmds:
      - uv run gunicorn --config {{.ROOT_DIR}}/config/gunicorn.conf.py camply_web.app:app
    env:
      GUNICORN_RELOAD: "1"

  ########################
  # INTERNAL TASKS
  ########################
  sync:
    desc: Install Project Dependencies
    internal: true
    cmds:
      - uv sync --all-extras
  pre-commit-install:
    desc: Install Pre-Commit Hooks
    internal: true
    cmds:
      - cmd: |
          if [ "{{.SKIP_PRECOMMIT | default 0}}" = "0" ]; then
              uv tool run --isolated pre-commit install --install-hooks
          fi
        silent: true
    status:
      - test ! -f {{.ROOT_DIR}}/.pre-commit-config.yaml
