"""
init

Revision ID: 067d9d721253
Revises:
Create Date: 2025-08-08 03:22:08.178631+00:00
"""

from textwrap import dedent
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "067d9d721253"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=32768), nullable=True),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_providers_name"), "providers", ["name"], unique=True)
    # ### end Alembic commands ###
    recreation_dot_gov_description = """
    Recreation.gov is the government's centralized travel planning platform and reservation
    system for 14 federal agencies, offering the tools, tips, and information needed for you
    to discover destinations and activities, plan a trip, and explore outdoor and cultural
    destinations in your zip code and across the country. Find and reserve incredible experiences
    that help you bring home a story through Recreation.gov!
    """
    # dedent and unwrap the description to ensure proper formatting
    recreation_dot_gov_description = (
        dedent(recreation_dot_gov_description)
        .strip()
        .replace("\n", " ")
        .replace("  ", " ")
    )
    rec_dot_gov_insert = sa.insert(
        sa.table(
            "providers",
            sa.column("name"),
            sa.column("description"),
            sa.column("url"),
            sa.column("enabled"),
        )
    ).values(
        name="Recreation.gov",
        description=recreation_dot_gov_description,
        url="https://www.recreation.gov",
        enabled=True,
    )
    op.execute(rec_dot_gov_insert)


def downgrade() -> None:
    """
    Downgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_providers_name"), table_name="providers")
    op.drop_table("providers")
    # ### end Alembic commands ###
