"""
search

Revision ID: 4cedc8e5fa20
Revises: 624a4720b8c3
Create Date: 2025-08-10 15:27:58.273690+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cedc8e5fa20"
down_revision: Union[str, Sequence[str], None] = "624a4720b8c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=128), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("provider_name", sa.String(length=128), nullable=False),
        sa.Column("recreation_area_id", sa.String(length=128), nullable=True),
        sa.Column("recreation_area_name", sa.String(length=128), nullable=True),
        sa.Column("campground_id", sa.String(length=128), nullable=True),
        sa.Column("campground_name", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_search_campground_name"), "search", ["campground_name"], unique=False
    )
    op.create_index(
        op.f("ix_search_recreation_area_name"),
        "search",
        ["recreation_area_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_recreation_area_name"), table_name="search")
    op.drop_index(op.f("ix_search_campground_name"), table_name="search")
    op.drop_table("search")
    # ### end Alembic commands ###
