"""
campgrounds

Revision ID: 5f55e2f6a836
Revises: 5d73123f56dd
Create Date: 2025-08-07 04:42:23.927659+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f55e2f6a836"
down_revision: Union[str, Sequence[str], None] = "5d73123f56dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campgrounds",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("recreation_area_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("county", sa.String(length=50), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("reservable", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recreation_area_id"],
            ["recreation_areas.id"],
        ),
        sa.PrimaryKeyConstraint("id", "recreation_area_id"),
    )
    op.create_index(op.f("ix_campgrounds_name"), "campgrounds", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_campgrounds_name"), table_name="campgrounds")
    op.drop_table("campgrounds")
    # ### end Alembic commands ###
