"""
city

Revision ID: d8923fc28e9e
Revises: 4cedc8e5fa20
Create Date: 2025-08-13 03:31:31.425244+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8923fc28e9e"
down_revision: Union[str, Sequence[str], None] = "4cedc8e5fa20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campgrounds", sa.Column("city", sa.String(length=50), nullable=True))
    op.add_column(
        "recreation_areas", sa.Column("city", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recreation_areas", "city")
    op.drop_column("campgrounds", "city")
    # ### end Alembic commands ###
