[project]
name = "providers"
version = "0.1.0"
dependencies = [
  # First Party
  "db",
  # Third Party
  "pydantic>=2,<3",
  "httpx>=0.28.0,<0.29.0",
  "platformdirs>=4,<5",
  "structlog>=25,<26",
  "rich>=14,<15",
  "click>=8,<9"
]

[project.scripts]
populate-database = "providers.cli:populate_database"

[dependency-groups]
dev = [
  "pytest>=8,<9",
  "pytest-cov>=6,<7",
  "ruff>=0.11.0,<0.12.0",
  "mypy>=1,<2",
  "pip>=24,<25"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["providers"]
