blank_issues_enabled: false
contact_links:
    -   name:  Have a question about how to use camply?
        url:   https://github.com/juftin/camply/discussions
        about: Check out camply discussions. There's lots of useful stuff there.