[project]
name = "db"
version = "0.1.0"
dependencies = [
  "sqlalchemy[asyncio]>=2,<3",
  "psycopg[binary]>=3,<4",
  "pydantic-settings>=2,<3"
]

[dependency-groups]
dev = [
  "pytest>=8,<9",
  "pytest-cov>=6,<7",
  "ruff>=0.11.0,<0.12.0",
  "mypy>=1,<2",
  "pip>=24,<25",
  "alembic>=1,<2"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["db"]
