name: Labeler

on:
    issues:
        types: [opened]

jobs:
    apply-triage-label:
        if: github.event_name == 'issues'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v6
              with:
                  script: |
                      github.rest.issues.addLabels({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        labels: ['triage']
                      })
