name: Release
on:
    push:
        branches: [main, next, beta, alpha, "*.x"]
concurrency:
    group: ${{ github.workflow }}
jobs:
    release:
        name: Release
        if: github.repository_owner == 'juftin'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2
                  ref: main
            - name: Setup Node.js
              uses: actions/setup-node@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install Hatch
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -q hatch pre-commit
                  hatch -v env create
                  hatch --version
            - name: Release
              run: hatch run gen:release
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  GIT_AUTHOR_NAME: github-actions[bot]
                  GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
                  GIT_COMMITTER_NAME: github-actions[bot]
                  GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com

    github-pages-publish:
        runs-on: ubuntu-latest
        needs: release
        if: github.ref == 'refs/heads/main' && github.repository_owner == 'juftin'
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Checkout Latest Changes
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}
                  fetch-depth: 0
            - name: Set up Python Environment
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install Hatch
              run: |
                  python -m pip install --upgrade pip wheel
                  python -m pip install -q hatch pre-commit
                  hatch --version
            - name: Create Virtual Environment
              run: hatch env create docs
            - name: Build Site
              run: hatch run docs:build
            - name: Setup GitHub Pages
              uses: actions/configure-pages@v4
            - name: Upload Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: site/
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
