name: camply Publishing

on:
    release:
        types: [ published ]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

            -   uses: actions/checkout@v2

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Declare Version Variable
                run:  |
                      cd ${GITHUB_WORKSPACE}
                      VERSION=$(grep -o  '__version__ = .*' camply/__init__.py | sed "s/__version__ = //g" | sed 's/"//g')
                      echo CAMPLY_LATEST_VERSION=${VERSION} >> $GITHUB_ENV

            -   name: Docker Image Building and Publishing
                id:   docker_build
                uses: docker/build-push-action@v2
                with:
                    push: True
                    tags: juftin/camply:latest,juftin/camply:${{ env.CAMPLY_LATEST_VERSION }}

            -   name: Build and Publish to PyPi
                run:  |
                      python -m pip install --upgrade pip
                      python -m pip install poetry
                      poetry update
                      cd ${GITHUB_WORKSPACE} && poetry install
                      cd ${GITHUB_WORKSPACE} && poetry build
                      cd ${GITHUB_WORKSPACE} && poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
