name: Docker Image CI

on:
    push:
        branches: [ "**" ]
    pull_request:
        branches: [ main ]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Declare Version Variable
                run:  echo "CAMPLY_LATEST_VERSION=$(grep -o  '__version__ = .*' camply/__init__.py | sed "s/__version__ = //g" | sed 's/"//g')" >> $GITHUB_ENV

            -   name: Docker Image Building
                id:   docker_build
                uses: docker/build-push-action@v2
                with:
                    push: False
                    tags: juftin/camply:latest,juftin/camply:${CAMPLY_LATEST_VERSION}

            -   name: Image digest
                run:  echo ${{ steps.docker_build.outputs.digest }}

            -   name: Build the Poetry Package
                run:  |
                      python -m pip install --upgrade pip
                      python -m pip install poetry
                      poetry update
                      poetry install
                      poetry build