name: Docker Image CI

on:
    push:
        branches: [ camply ]
    pull_request:
        branches: [ camply ]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Build the Docker image
                run:  docker build . --file Dockerfile --tag juftin/camply:$(date +%s)