name: Docker CI/CD

on:
    pull_request:
        branches: ["**"]
        paths:
            - camply/**
            - pyproject.toml
            - .github/workflows/docker.yaml
            - Dockerfile
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    docker-ci-test:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Github Workspace
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"
            - name: Install Hatch
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -q hatch
                  hatch env create
                  hatch --version
            - name: Declare Version Variable
              run: |
                  PACKAGE_VERSION=$(hatch version)
                  PACKAGE_NAME=$(hatch project metadata | jq -r .name)
                  echo PACKAGE_VERSION=${PACKAGE_VERSION} >> $GITHUB_ENV
                  echo PACKAGE_NAME=${PACKAGE_NAME} >> $GITHUB_ENV
            - name: Docker Image Building and Publishing
              id: docker_build
              uses: docker/build-push-action@v3
              with:
                  push: false
                  tags: juftin/${{ env.PACKAGE_NAME }}:latest
