name: docker

on:
    pull_request:
        paths:
            - camply/**
            - pyproject.toml
            - .github/workflows/docker.yaml
            - Dockerfile
            - uv.lock
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: docker
              uses: juftin/actions/taskfile@v1
              with:
                  checkout: true
                  setup-uv: true
                  task: docker
                  buildx: true
                  github-token: ${{ secrets.GITHUB_TOKEN }}
