name: Lint

on:
    pull_request:
        branches: ["**"]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Github Workspace
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set up Python Environment 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"
            - name: Install Hatch
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -q hatch
                  hatch env create
                  hatch --version
            - name: Lint
              id: lint
              continue-on-error: true
              run: |
                  echo "::add-matcher::.github/matchers/flake8.json"
                  hatch run lint
                  echo "::remove-matcher owner=flake8::"
            - name: Code Checker
              id: check
              continue-on-error: true
              run: |
                  echo "::add-matcher::.github/matchers/mypy.json"
                  hatch run check
                  echo "::remove-matcher owner=mypy::"
            - name: Raise Errors For Linting Failures
              if: |
                  steps.lint.outcome != 'success'
              run: |
                  echo "Lint: ${{ steps.lint.outcome }}"
                  echo "Check: ${{ steps.check.outcome }}"
                  echo "I Should Really Be Enforcing MyPy Errors"
                  exit 1
