name: Lint

on:
    pull_request:
        branches: ["**"]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Github Workspace
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set up Python Environment 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Install Python Dependencies
              run: |
                  python -m pip install --upgrade pip wheel
                  python -m pip install tox
            - name: Lint
              id: lint
              continue-on-error: true
              run: |
                  echo "::add-matcher::.github/matchers/flake8.json"
                  tox -e lint
                  echo "::remove-matcher owner=flake8::"
            - name: Lint with MyPy
              id: mypy
              continue-on-error: true
              run: |
                  echo "::add-matcher::.github/matchers/mypy.json"
                  tox -e mypy
                  echo "::remove-matcher owner=mypy::"
            - name: Raise Errors For Linting Failures
              if: |
                  steps.lint.outcome != 'success'
              run: |
                  echo "Lint: ${{ steps.lint.outcome }}"
                  echo "MyPy: ${{ steps.mypy.outcome }}"
                  echo "I Should Really Be Enforcing MyPy Errors"
                  exit 1
