name: Version Checker

on:
    pull_request:
        branches: [ main ]
jobs:
    version-checker:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: "3.9"
            -   name: Install Dependencies
                run:  |
                      pip install --upgrade pip
                      pip install packaging
            -   name: Checkout Main Branch
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
                    ref:         main
            -   name: Get Version from main
                run:  |
                      COMPARED_VERSION="$(python setup.py --version)"
                      echo COMPARED_VERSION="${COMPARED_VERSION}" >> ${GITHUB_ENV}
            -   name: Checkout Current Ref
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
                    ref:         ${{ github.ref }}
            -   name: Get Current Version
                run:  |
                      CURRENT_VERSION="$(python setup.py --version)"
                      echo CURRENT_VERSION="${CURRENT_VERSION}" >> ${GITHUB_ENV}
            -   name: Compare Versions
                run:  |
                      python "${{ github.workspace }}/.github/helpers/version_check.py"
